import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/app/components/dashboard/ThemeProvider";
import {Toaster} from "@/componentsFrontend/ui/sonner"
import AIChatGeneral from "@/componentsFrontend/AI/SQL/AIwidget";

const inter = Inter({ subsets: ["latin"] });
//nothing delete
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {children}
           
           <Toaster richColors closeButton/>
           </ThemeProvider>
      </body>
    </html>
  );
}
