import type { TgemInvoice } from "@/components/client-flows/tgem/invoice-approval/types";

export const TGEM_MOCK_INVOICES: TgemInvoice[] = [
  {
    id: "inv-001",
    number: "TG-2026-0718",
    supplier: "Baltic Electrical Systems SIA",
    supplierRegNo: "40203188910",
    project: "TGEM Office Reconstruction",
    contract: "EL-24-118",
    receivedDate: "2026-07-01",
    dueDate: "2026-07-15",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 18420,
    vat: 3868.2,
    total: 22288.2,
    status: "In approval",
    risk: "Medium",
    paymentTerm: "14 days",
    bankAccount: "LV80HABA0551047890201",
    reference: "Stage 2 electrical installation",
    lines: [
      {
        id: "line-1",
        description: "Cable tray installation, level 2",
        quantity: 420,
        unit: "m",
        unitPrice: 18,
        total: 7560,
      },
      {
        id: "line-2",
        description: "Switchboard assembly and testing",
        quantity: 3,
        unit: "pcs",
        unitPrice: 1650,
        total: 4950,
      },
      {
        id: "line-3",
        description: "Lighting circuit installation",
        quantity: 197,
        unit: "point",
        unitPrice: 30,
        total: 5910,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Project manager",
        person: "Laura Berzina",
        status: "approved",
        dueDate: "2026-07-02",
        comment: "Quantities match June progress report.",
      },
      {
        id: "step-2",
        role: "Cost controller",
        person: "Miks Ozols",
        status: "current",
        dueDate: "2026-07-03",
      },
      {
        id: "step-3",
        role: "Finance",
        person: "Anna Liepa",
        status: "waiting",
        dueDate: "2026-07-05",
      },
      {
        id: "step-4",
        role: "Board approval",
        person: "Janis Krumins",
        status: "waiting",
        dueDate: "2026-07-08",
      },
    ],
  },
  {
    id: "inv-002",
    number: "TG-2026-0719",
    supplier: "Concrete Logistics SIA",
    supplierRegNo: "40103900211",
    project: "TGEM Warehouse Extension",
    contract: "CW-25-044",
    receivedDate: "2026-07-01",
    dueDate: "2026-07-20",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 32700,
    vat: 6867,
    total: 39567,
    status: "Needs review",
    risk: "High",
    paymentTerm: "20 days",
    bankAccount: "LV12RIKO0002938854212",
    reference: "Foundation works, batch B",
    lines: [
      {
        id: "line-1",
        description: "Ready-mix concrete C30/37",
        quantity: 310,
        unit: "m3",
        unitPrice: 82,
        total: 25420,
      },
      {
        id: "line-2",
        description: "Pump service",
        quantity: 28,
        unit: "h",
        unitPrice: 145,
        total: 4060,
      },
      {
        id: "line-3",
        description: "Transport surcharge",
        quantity: 92,
        unit: "trip",
        unitPrice: 35,
        total: 3220,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Site manager",
        person: "Edgars Kalnins",
        status: "current",
        dueDate: "2026-07-03",
      },
      {
        id: "step-2",
        role: "Project manager",
        person: "Laura Berzina",
        status: "waiting",
        dueDate: "2026-07-05",
      },
      {
        id: "step-3",
        role: "Finance",
        person: "Anna Liepa",
        status: "waiting",
        dueDate: "2026-07-08",
      },
    ],
  },
  {
    id: "inv-003",
    number: "TG-2026-0720",
    supplier: "Nordic HVAC Group",
    supplierRegNo: "40003874121",
    project: "TGEM Office Reconstruction",
    contract: "HVAC-24-072",
    receivedDate: "2026-06-28",
    dueDate: "2026-07-12",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 9800,
    vat: 2058,
    total: 11858,
    status: "Approved",
    risk: "Low",
    paymentTerm: "14 days",
    bankAccount: "LV44UNLA0050012345678",
    reference: "Ventilation balancing works",
    lines: [
      {
        id: "line-1",
        description: "Air balancing and measurement",
        quantity: 56,
        unit: "h",
        unitPrice: 95,
        total: 5320,
      },
      {
        id: "line-2",
        description: "Commissioning report package",
        quantity: 1,
        unit: "set",
        unitPrice: 4480,
        total: 4480,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Project manager",
        person: "Laura Berzina",
        status: "approved",
        dueDate: "2026-06-29",
        comment: "Accepted.",
      },
      {
        id: "step-2",
        role: "Finance",
        person: "Anna Liepa",
        status: "approved",
        dueDate: "2026-07-01",
        comment: "Ready for payment batch.",
      },
    ],
  },
];
