import type { TgemInvoice } from "@/flows/tgem-invoice-approval/frontend/types";

export const TGEM_MOCK_INVOICES: TgemInvoice[] = [
  {
    id: "inv-001",
    number: "TG-2026-0718",
    supplier: "Baltic Electrical Systems SIA",
    supplierRegNo: "40203188910",
    project: "TGEM Office Reconstruction",
    contract: "EL-24-118",
    receivedDate: "2026-07-01",
    dueDate: "2026-07-15",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 18420,
    vat: 3868.2,
    total: 22288.2,
    status: "In approval",
    risk: "Medium",
    paymentTerm: "14 days",
    bankAccount: "LV80HABA0551047890201",
    reference: "Stage 2 electrical installation",
    lines: [
      {
        id: "line-1",
        description: "Cable tray installation, level 2",
        quantity: 420,
        unit: "m",
        unitPrice: 18,
        total: 7560,
      },
      {
        id: "line-2",
        description: "Switchboard assembly and testing",
        quantity: 3,
        unit: "pcs",
        unitPrice: 1650,
        total: 4950,
      },
      {
        id: "line-3",
        description: "Lighting circuit installation",
        quantity: 197,
        unit: "point",
        unitPrice: 30,
        total: 5910,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Project manager",
        person: "Laura Berzina",
        status: "approved",
        dueDate: "2026-07-02",
        comment: "Quantities match June progress report.",
      },
      {
        id: "step-2",
        role: "Cost controller",
        person: "Miks Ozols",
        status: "current",
        dueDate: "2026-07-03",
      },
      {
        id: "step-3",
        role: "Finance",
        person: "Anna Liepa",
        status: "waiting",
        dueDate: "2026-07-05",
      },
      {
        id: "step-4",
        role: "Board approval",
        person: "Janis Krumins",
        status: "waiting",
        dueDate: "2026-07-08",
      },
    ],
  },
  {
    id: "inv-002",
    number: "TG-2026-0719",
    supplier: "Concrete Logistics SIA",
    supplierRegNo: "40103900211",
    project: "TGEM Warehouse Extension",
    contract: "CW-25-044",
    receivedDate: "2026-07-01",
    dueDate: "2026-07-20",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 32700,
    vat: 6867,
    total: 39567,
    status: "Needs review",
    risk: "High",
    paymentTerm: "20 days",
    bankAccount: "LV12RIKO0002938854212",
    reference: "Foundation works, batch B",
    lines: [
      {
        id: "line-1",
        description: "Ready-mix concrete C30/37",
        quantity: 310,
        unit: "m3",
        unitPrice: 82,
        total: 25420,
      },
      {
        id: "line-2",
        description: "Pump service",
        quantity: 28,
        unit: "h",
        unitPrice: 145,
        total: 4060,
      },
      {
        id: "line-3",
        description: "Transport surcharge",
        quantity: 92,
        unit: "trip",
        unitPrice: 35,
        total: 3220,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Site manager",
        person: "Edgars Kalnins",
        status: "current",
        dueDate: "2026-07-03",
      },
      {
        id: "step-2",
        role: "Project manager",
        person: "Laura Berzina",
        status: "waiting",
        dueDate: "2026-07-05",
      },
      {
        id: "step-3",
        role: "Finance",
        person: "Anna Liepa",
        status: "waiting",
        dueDate: "2026-07-08",
      },
    ],
  },
  {
    id: "inv-003",
    number: "TG-2026-0720",
    supplier: "Nordic HVAC Group",
    supplierRegNo: "40003874121",
    project: "TGEM Office Reconstruction",
    contract: "HVAC-24-072",
    receivedDate: "2026-06-28",
    dueDate: "2026-07-12",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 9800,
    vat: 2058,
    total: 11858,
    status: "Approved",
    risk: "Low",
    paymentTerm: "14 days",
    bankAccount: "LV44UNLA0050012345678",
    reference: "Ventilation balancing works",
    lines: [
      {
        id: "line-1",
        description: "Air balancing and measurement",
        quantity: 56,
        unit: "h",
        unitPrice: 95,
        total: 5320,
      },
      {
        id: "line-2",
        description: "Commissioning report package",
        quantity: 1,
        unit: "set",
        unitPrice: 4480,
        total: 4480,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Project manager",
        person: "Laura Berzina",
        status: "approved",
        dueDate: "2026-06-29",
        comment: "Accepted.",
      },
      {
        id: "step-2",
        role: "Finance",
        person: "Anna Liepa",
        status: "approved",
        dueDate: "2026-07-01",
        comment: "Ready for payment batch.",
      },
    ],
  },
  {
    id: "inv-004",
    number: "TG-2026-0721",
    supplier: "SteelWorks Baltics SIA",
    supplierRegNo: "40203451290",
    project: "TGEM Warehouse Extension",
    contract: "ST-25-061",
    receivedDate: "2026-07-02",
    dueDate: "2026-07-17",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 21450,
    vat: 4504.5,
    total: 25954.5,
    status: "In approval",
    risk: "Medium",
    paymentTerm: "15 days",
    bankAccount: "LV10PARX0001234567890",
    reference: "Roof steel connection plates",
    lines: [
      {
        id: "line-1",
        description: "Galvanized connection plates",
        quantity: 780,
        unit: "kg",
        unitPrice: 12.5,
        total: 9750,
      },
      {
        id: "line-2",
        description: "Anchor bolt sets",
        quantity: 240,
        unit: "set",
        unitPrice: 18,
        total: 4320,
      },
      {
        id: "line-3",
        description: "Workshop drilling and marking",
        quantity: 82,
        unit: "h",
        unitPrice: 90,
        total: 7380,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Site manager",
        person: "Edgars Kalnins",
        status: "approved",
        dueDate: "2026-07-03",
        comment: "Delivery note checked.",
      },
      {
        id: "step-2",
        role: "Cost controller",
        person: "Miks Ozols",
        status: "current",
        dueDate: "2026-07-05",
      },
      {
        id: "step-3",
        role: "Finance",
        person: "Anna Liepa",
        status: "waiting",
        dueDate: "2026-07-08",
      },
    ],
  },
  {
    id: "inv-005",
    number: "TG-2026-0722",
    supplier: "Riga Equipment Rental",
    supplierRegNo: "40103445521",
    project: "TGEM Logistics Yard",
    contract: "EQ-26-009",
    receivedDate: "2026-07-03",
    dueDate: "2026-07-10",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 6240,
    vat: 1310.4,
    total: 7550.4,
    status: "Needs review",
    risk: "Low",
    paymentTerm: "7 days",
    bankAccount: "LV23HABA0551047770009",
    reference: "Telehandler and scissor lift rental",
    lines: [
      {
        id: "line-1",
        description: "Telehandler 17m rental",
        quantity: 12,
        unit: "day",
        unitPrice: 320,
        total: 3840,
      },
      {
        id: "line-2",
        description: "Scissor lift rental",
        quantity: 10,
        unit: "day",
        unitPrice: 180,
        total: 1800,
      },
      {
        id: "line-3",
        description: "Delivery and pickup",
        quantity: 2,
        unit: "trip",
        unitPrice: 300,
        total: 600,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Site manager",
        person: "Edgars Kalnins",
        status: "current",
        dueDate: "2026-07-04",
      },
      {
        id: "step-2",
        role: "Finance",
        person: "Anna Liepa",
        status: "waiting",
        dueDate: "2026-07-07",
      },
    ],
  },
  {
    id: "inv-006",
    number: "TG-2026-0723",
    supplier: "CleanSite Services SIA",
    supplierRegNo: "40202990177",
    project: "TGEM Office Reconstruction",
    contract: "FM-24-033",
    receivedDate: "2026-07-03",
    dueDate: "2026-07-18",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 3120,
    vat: 655.2,
    total: 3775.2,
    status: "Approved",
    risk: "Low",
    paymentTerm: "15 days",
    bankAccount: "LV55RIKO0002938840001",
    reference: "Post-construction cleaning, level 1",
    lines: [
      {
        id: "line-1",
        description: "Deep cleaning after finishing works",
        quantity: 1850,
        unit: "m2",
        unitPrice: 1.4,
        total: 2590,
      },
      {
        id: "line-2",
        description: "Waste bag handling",
        quantity: 53,
        unit: "bag",
        unitPrice: 10,
        total: 530,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Facilities lead",
        person: "Ieva Jansone",
        status: "approved",
        dueDate: "2026-07-04",
        comment: "Area accepted.",
      },
      {
        id: "step-2",
        role: "Finance",
        person: "Anna Liepa",
        status: "approved",
        dueDate: "2026-07-05",
      },
    ],
  },
  {
    id: "inv-007",
    number: "TG-2026-0724",
    supplier: "GlassPro Latvia",
    supplierRegNo: "40103777454",
    project: "TGEM Office Reconstruction",
    contract: "GL-24-099",
    receivedDate: "2026-07-04",
    dueDate: "2026-07-24",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 14680,
    vat: 3082.8,
    total: 17762.8,
    status: "In approval",
    risk: "High",
    paymentTerm: "20 days",
    bankAccount: "LV70UNLA0050011112223",
    reference: "Interior glass partitions, variation 03",
    lines: [
      {
        id: "line-1",
        description: "Tempered glass partitions",
        quantity: 128,
        unit: "m2",
        unitPrice: 92,
        total: 11776,
      },
      {
        id: "line-2",
        description: "Aluminium profiles and seals",
        quantity: 88,
        unit: "m",
        unitPrice: 22,
        total: 1936,
      },
      {
        id: "line-3",
        description: "Site installation adjustment",
        quantity: 11,
        unit: "h",
        unitPrice: 88,
        total: 968,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Project manager",
        person: "Laura Berzina",
        status: "approved",
        dueDate: "2026-07-05",
      },
      {
        id: "step-2",
        role: "Commercial manager",
        person: "Rihards Sprogis",
        status: "current",
        dueDate: "2026-07-08",
      },
      {
        id: "step-3",
        role: "Finance",
        person: "Anna Liepa",
        status: "waiting",
        dueDate: "2026-07-11",
      },
    ],
  },
  {
    id: "inv-008",
    number: "TG-2026-0725",
    supplier: "Security Systems Nord",
    supplierRegNo: "40003993002",
    project: "TGEM Logistics Yard",
    contract: "SEC-26-014",
    receivedDate: "2026-07-05",
    dueDate: "2026-07-19",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 12890,
    vat: 2706.9,
    total: 15596.9,
    status: "Needs review",
    risk: "Medium",
    paymentTerm: "14 days",
    bankAccount: "LV61HABA0551045551000",
    reference: "Access control gate installation",
    lines: [
      {
        id: "line-1",
        description: "Vehicle gate controller",
        quantity: 2,
        unit: "pcs",
        unitPrice: 2750,
        total: 5500,
      },
      {
        id: "line-2",
        description: "Card readers and setup",
        quantity: 8,
        unit: "pcs",
        unitPrice: 420,
        total: 3360,
      },
      {
        id: "line-3",
        description: "Cable and commissioning works",
        quantity: 62,
        unit: "h",
        unitPrice: 65,
        total: 4030,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Operations",
        person: "Ieva Jansone",
        status: "current",
        dueDate: "2026-07-06",
      },
      {
        id: "step-2",
        role: "IT security",
        person: "Kaspars Eglitis",
        status: "waiting",
        dueDate: "2026-07-09",
      },
      {
        id: "step-3",
        role: "Finance",
        person: "Anna Liepa",
        status: "waiting",
        dueDate: "2026-07-12",
      },
    ],
  },
  {
    id: "inv-009",
    number: "TG-2026-0726",
    supplier: "GeoSurvey Pro",
    supplierRegNo: "40203123456",
    project: "TGEM Warehouse Extension",
    contract: "SUR-25-018",
    receivedDate: "2026-07-06",
    dueDate: "2026-07-21",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 4560,
    vat: 957.6,
    total: 5517.6,
    status: "Approved",
    risk: "Low",
    paymentTerm: "15 days",
    bankAccount: "LV37PARX0009992221110",
    reference: "As-built surveying and reports",
    lines: [
      {
        id: "line-1",
        description: "Surveyor field work",
        quantity: 24,
        unit: "h",
        unitPrice: 95,
        total: 2280,
      },
      {
        id: "line-2",
        description: "As-built drawing package",
        quantity: 1,
        unit: "set",
        unitPrice: 2280,
        total: 2280,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Site manager",
        person: "Edgars Kalnins",
        status: "approved",
        dueDate: "2026-07-07",
      },
      {
        id: "step-2",
        role: "Finance",
        person: "Anna Liepa",
        status: "approved",
        dueDate: "2026-07-08",
      },
    ],
  },
  {
    id: "inv-010",
    number: "TG-2026-0727",
    supplier: "FireSafe Engineering",
    supplierRegNo: "40103888444",
    project: "TGEM Office Reconstruction",
    contract: "FS-24-045",
    receivedDate: "2026-07-06",
    dueDate: "2026-07-22",
    servicePeriod: "2026-06",
    currency: "EUR",
    subtotal: 8950,
    vat: 1879.5,
    total: 10829.5,
    status: "In approval",
    risk: "Medium",
    paymentTerm: "16 days",
    bankAccount: "LV19RIKO0002938833300",
    reference: "Fire alarm loop testing",
    lines: [
      {
        id: "line-1",
        description: "Detector loop testing",
        quantity: 340,
        unit: "device",
        unitPrice: 18,
        total: 6120,
      },
      {
        id: "line-2",
        description: "Panel configuration",
        quantity: 14,
        unit: "h",
        unitPrice: 95,
        total: 1330,
      },
      {
        id: "line-3",
        description: "Compliance report",
        quantity: 1,
        unit: "set",
        unitPrice: 1500,
        total: 1500,
      },
    ],
    approvals: [
      {
        id: "step-1",
        role: "Safety manager",
        person: "Kaspars Eglitis",
        status: "approved",
        dueDate: "2026-07-07",
      },
      {
        id: "step-2",
        role: "Project manager",
        person: "Laura Berzina",
        status: "current",
        dueDate: "2026-07-09",
      },
      {
        id: "step-3",
        role: "Finance",
        person: "Anna Liepa",
        status: "waiting",
        dueDate: "2026-07-12",
      },
    ],
  },
];
