
// /C:\Users\user\MainProjects\Buvconsult-deploy\buvconsult\app\layout.tsx

import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/dashboard/ThemeProvider";
import {Toaster} from "@/components/ui/sonner"
import {GoogleTagManager, GoogleAnalytics} from '@next/third-parties/google'
import Script from "next/script";



const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Construction data managment",
  description: "Generated by create next app",
  manifest: "/site.webmanifest",
  icons: {
    icon: [
      { url: "/favicon/favicon.ico", sizes: "any" },
      { url: "/favicon/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon/favicon-48x48.png", sizes: "48x48", type: "image/png" },
    ],
    apple: [
      { url: "/favicon/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const idGa = process.env.NEXT_PUBLIC_GA_ID as string

  

  return (
    <html lang="en">
            
              <GoogleTagManager gtmId="GTM-TSLDCSGF" />


      

      <body
        className={`${inter.className}  antialiased`}
      >
       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            

            
        {children}
 
   
           
           <Toaster richColors closeButton/>
           </ThemeProvider>
      </body>
    </html>
  );
}
