
// /C:\Users\user\MainProjects\Buvconsult-deploy\buvconsult\app\layout.tsx

import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/dashboard/ThemeProvider";
import {Toaster} from "@/components/ui/sonner"
import {GoogleTagManager, GoogleAnalytics} from '@next/third-parties/google'
import Script from "next/script";



const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Construction data managment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const idGa = process.env.NEXT_PUBLIC_GA_ID as string

  

  return (
    <html lang="en">
            
             {/* <GoogleTagManager gtmId="GTM-TFB37MS4" />


            <Script id="ga-ads-config" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('config', 'AW-17670426077');
        `}
      </Script> */}

      <body
        className={`${inter.className}  antialiased`}
      >
       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            

            
        {children}
 
   
           
           <Toaster richColors closeButton/>
           </ThemeProvider>
      </body>
    </html>
  );
}
